#!/bin/bash
# script to uninstall the insalled docker engine and install the latest docker engine 
# version 2025-01-30, written by https://github.com/TheHappyEndL

# Check if sudo can be used or not

echo "[?] Checking if sudo is installed and can be used...
if ! command -v sudo &> /dev/null
then
    echo "[!] sudo is not installed. Some commands may fail."
	sudoInstalled=false
else
	sudoInstalled=true
fi

# Sets sudo or leaves empty string

echo "[+]Placing 'sudo' where needed..."
if [ "$sudoInstalled" = true ]; 
then
	addSudo="sudo"
	echo "[✓] sudo added."
else
	addSudo = ""
fi

# [?] Check if Docker is installed... 

if command -v docker &> /dev/null
then
	echo "[!] Docker is installed. Uninstalling...
	for pkg in docker.io docker-doc docker-compose podman-docker containerd runc; do $addSudo apt-get remove $pkg; done
	echo "[✓] Docker succesfully uninstalled."
else
	echo "[!] Docker is not installed. Proceeding with installation..."
fi

# Setting up Dockers apt repository


echo "[+] Getting Docker's official GPG key..."
"$addSudo" apt-get update
"$addSudo" apt-get install ca-certificates curl
"$addSudo" install -m 0755 -d /etc/apt/keyrings
"$addSudo" curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
"$addSudo" chmod a+r /etc/apt/keyrings/docker.asc

echo "[✓] GPG key successfully added."

# Adding repository to apt sources

echo "[+] Adding repository to apt sources..."
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  "$addSudo" tee /etc/apt/sources.list.d/docker.list > /dev/null

echo "[✓] Successfully added the repository to apt sources."
echo "[+] Updating repository..."
"$addSudo" apt-get update

# Installing the latest Docker version and dependencies

echo "[+] Installing Docker..."
"$addSudo" apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin

# Verifying Installation

echo "[?] Checking Docker Installation
"$addSudo" docker run hello-world &> /dev/null

if [ $? -eq 0 ]; then
    echo "[✓]Docker is working correctly. Installation complete. Exiting Script."
    # Proceed with the rest of your code
else
    echo "[!] Docker failed to run the hello-world container."
    exit 1  # 
fi
